### ISSUE TITLE
PlotSquared v5 support not work

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#65] opened 2020-04-21 13:21 UTC
```
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] Loading Protection Modules...
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] This may happen more than once.
[15:19:17] [Server thread/WARN]: [CS-CoreLib] Loaded class com.sk89q.worldguard.bukkit.WorldGuardPlugin from WorldGuard v7.0.2-SNAPSHOT;bf2593e which is not a depend, softdepend or loadbefore of this plugin.
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] Loaded Protection Module "WorldGuard"
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] Loaded Protection Module "PlotSquared v5"
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] Loading Protection Modules...
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] This may happen more than once.
[15:19:17] [Server thread/WARN]: [Slimefun] Loaded class com.sk89q.worldguard.bukkit.WorldGuardPlugin from WorldGuard v7.0.2-SNAPSHOT;bf2593e which is not a depend, softdepend or loadbefore of this plugin.
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] Loaded Protection Module "WorldGuard"
[15:19:17] [Server thread/INFO]: [CS-CoreLib2] [CS-CoreLib2 - Protection] Loaded Protection Module "PlotSquared"
```

```
[15:19:27] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to Slimefun vDEV - 486 (git b013247e)
java.lang.NoClassDefFoundError: com/github/intellectualsites/plotsquared/plot/object/Location
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.PlotSquaredProtectionModule.hasPermission(PlotSquaredProtectionModule.java:31) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:192) ~[?:?]
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AGenerator$1.canOpen(AGenerator.java:54) ~[?:?]
	at me.mrCookieSlime.Slimefun.api.inventory.DirtyChestMenu.canOpen(DirtyChestMenu.java:44) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunItemListener.onRightClick(SlimefunItemListener.java:97) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor93.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-183]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:463) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerInteractManager.a(PlayerInteractManager.java:450) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1378) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:27) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PacketPlayInUseItem.a(PacketPlayInUseItem.java:5) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1059) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1052) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1022) ~[patched_1.15.2.jar:git-Paper-183]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:945) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: java.lang.ClassNotFoundException: com.github.intellectualsites.plotsquared.plot.object.Location
	at java.net.URLClassLoader.findClass(URLClassLoader.java:471) ~[?:?]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Paper-183]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Paper-183]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:588) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 26 more
```

PlotSquared version 5.8

**Comment by TheBusyBiscuit** [comment] 2020-04-21 13:22
Duplicate of #64

**Comment by andris155** [comment] 2020-04-21 13:26
I compiled the new updated version CS-CoreLib, but this don't fixed this error.

**Comment by TheBusyBiscuit** [comment] 2020-04-21 13:27
This is CS-CoreLib2, not CS-CoreLib...

**Closed by TheBusyBiscuit** 2020-04-21 13:27 UTC

**Comment by andris155** [comment] 2020-04-21 13:30
The CS-CoreLib issue tracker disabled...
And yes I used 0.14 version CS-CoreLib2 for compile the CS-CoreLib.

**Comment by TheBusyBiscuit** [comment] 2020-04-21 13:31
Just wait for the update...
This has nothing to do with CS-CoreLib...

**Comment by TheBusyBiscuit** [comment] 2020-04-21 13:44
As a final note on this...
You reported the issue and the issue was resolved.
You cannot test it until an update was pushed, so be patient...

Especially because you really do not seem to understand how this all works...
To be precise, this pull request carries the fix:
https://github.com/TheBusyBiscuit/Slimefun4/pull/1817

It has nothing to do with CS-CoreLib, it's CS-CoreLib2.
