### ISSUE TITLE
An Error occured while querying the Protection Module: "GriefPrevention"

### ISSUE THREAD

**Issue by andris155** [TheBusyBiscuit/CS-CoreLib2#66] opened 2020-04-22 19:33 UTC
```
[12:17:40] [Server thread/ERROR]: [CS-CoreLib2] [CS-CoreLib2 - Protection] An Error occured while querying the Protection Module: "GriefPrevention"
java.lang.NullPointerException: null
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.modules.GriefPreventionProtectionModule.hasPermission(GriefPreventionProtectionModule.java:40) ~[?:?]
	at me.mrCookieSlime.Slimefun.cscorelib2.protection.ProtectionManager.hasPermission(ProtectionManager.java:192) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunBootsListener.stomp(SlimefunBootsListener.java:79) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunBootsListener.lambda$new$1(SlimefunBootsListener.java:57) ~[?:?]
	at io.github.thebusybiscuit.slimefun4.implementation.listeners.SlimefunBootsListener.onDamage(SlimefunBootsListener.java:102) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor347.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-205]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-205]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.dealFallDamage(NoFall.java:239) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.handleOnGround(NoFall.java:117) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.touchDown(NoFall.java:393) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.player.NoFall.check(NoFall.java:336) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.MovingListener.checkPlayerMove(MovingListener.java:971) ~[?:?]
	at fr.neatmonster.nocheatplus.checks.moving.MovingListener.onPlayerMove(MovingListener.java:572) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor133.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at fr.neatmonster.nocheatplus.event.mini.MultiListenerRegistry$AutoListener.onEvent(MultiListenerRegistry.java:82) ~[?:?]
	at fr.neatmonster.nocheatplus.event.mini.MiniListenerNode.onEvent(MiniListenerNode.java:157) ~[?:?]
	at fr.neatmonster.nocheatplus.event.mini.EventRegistryBukkit$4.execute(EventRegistryBukkit.java:124) ~[?:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-205]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:1115) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying.a(SourceFile:122) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:56) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1077) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1070) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1144) ~[patched_1.15.2.jar:git-Paper-205]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-205]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

CS-CoreLib vDEV - 84 (git 0d29dbee)
Slimefun vDEV - 486 (git b013247e)

**Comment by TheBusyBiscuit** [comment] 2020-04-22 19:38
Duplicate of #50

**Closed by TheBusyBiscuit** 2020-04-22 19:38 UTC
